spring:
  liquibase:
#    url: jdbc:h2:mem:rsjug-koltin-todo-list;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:rsjug-koltin-todo-list
    drop-first: true
    user: sa
    password:
    driver-class-name: org.h2.Driver
    change-log: classpath:db/changelog/db.changelog-master.xml
